#!/bin/bash

rm test.econf
touch test.econf

confcrypt add --key ~/.ssh/confcrypt --name Test --type String --value Foobar test.econf > test.econf

RES=$(confcrypt add --key ~/.ssh/confcrypt --name Test2 --type Int --value 42 test.econf)
echo "$RES" > test.econf

confcrypt validate --key ~/.ssh/confcrypt test.econf

