name:                confcrypt
version:             0.2.2.0
github:              collegevine/confcrypt
license:             MIT
author:              "Chris Coffey"
maintainer:          "chris@collegevine.com"
copyright:           "2018 Chris Coffey, CollegeVine"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CollegeVine/confcrypt#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.14 && < 0.15
- text >= 1.2
- mtl >= 2.2 && < 2.3
- transformers
- megaparsec >= 7.0
- containers >= 0.5.11
- parser-combinators
- deepseq >= 1.4.3
- cryptonite >= 0.25
- crypto-pubkey-openssh
- crypto-pubkey-types
- bytestring >= 0.10.8 && < 0.11
- base64-bytestring
- amazonka >= 1.6 && < 1.7
- amazonka-kms >= 1.6 && < 1.7
- lens >= 4.16
- conduit >= 1.3 && < 1.4

# This tells clang not to print an ugly warning because we use a macro-generated module
ghc-options: ["-optP-Wno-nonportable-include-path"]

library:
  source-dirs: src
  exposed-modules:
    - ConfCrypt.Types
    - ConfCrypt.Parser
    - ConfCrypt.Commands
    - ConfCrypt.Encryption
    - ConfCrypt.Validation
    - ConfCrypt.Default
    - ConfCrypt.Providers.AWS
  default-extensions: MultiParamTypeClasses OverloadedStrings FlexibleContexts FlexibleInstances NamedFieldPuns
        TupleSections DeriveGeneric DeriveAnyClass FunctionalDependencies TypeApplications UndecidableInstances
        GADTs ConstraintKinds



executables:
  confcrypt:
    main:                Main.hs
    source-dirs:         app
    other-modules:
        - ConfCrypt.CLI.API
        - ConfCrypt.CLI.Engine
        - Paths_confcrypt
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - confcrypt
    - optparse-applicative
    default-extensions: MultiParamTypeClasses OverloadedStrings FlexibleContexts FlexibleInstances NamedFieldPuns
        TupleSections ExistentialQuantification TypeApplications UndecidableInstances BangPatterns ViewPatterns
        GADTs
tests:
  confcrypt-test:
    main:                Tests.hs
    source-dirs:
        - test
        - app
    other-modules:
        ConfCrypt.Parser.Tests,
        ConfCrypt.Commands.Tests,
        ConfCrypt.Encryption.Tests,
        ConfCrypt.CLI.API.Tests,
        ConfCrypt.Common,
        ConfCrypt.CLI.API
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - confcrypt
    - tasty
    - tasty-quickcheck
    - QuickCheck
    - tasty-hunit
    - HUnit
    - memory
    default-extensions: MultiParamTypeClasses OverloadedStrings FlexibleContexts FlexibleInstances NamedFieldPuns
        TupleSections
