name:                confcrypt
version:             0.1.0.1
github:              "https://github.com/collegevine/confcrypt"
license:             MIT
author:              "Chris Coffey"
maintainer:          "chris@collegevine.com"
copyright:           "2018 Chris Coffey, CollegeVine"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/CollegeVine/confcrypt#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- text
- mtl
- transformers
- megaparsec
- containers
- parser-combinators
- deepseq
- cryptonite
- crypto-pubkey-openssh
- crypto-pubkey-types
- bytestring
- base64-bytestring
- amazonka
- amazonka-kms
- lens
- conduit

library:
  source-dirs: src
  exposed-modules:
    - ConfCrypt.Types
    - ConfCrypt.Parser
    - ConfCrypt.Commands
    - ConfCrypt.Encryption
    - ConfCrypt.Validation
    - ConfCrypt.Default
    - ConfCrypt.Providers.AWS
  default-extensions: MultiParamTypeClasses OverloadedStrings FlexibleContexts FlexibleInstances NamedFieldPuns
        TupleSections DeriveGeneric DeriveAnyClass FunctionalDependencies TypeApplications UndecidableInstances
        GADTs ConstraintKinds



executables:
  confcrypt:
    main:                Main.hs
    source-dirs:         app
    other-modules:
        - ConfCrypt.CLI.API
        - ConfCrypt.CLI.Engine
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - confcrypt
    - optparse-applicative
    default-extensions: MultiParamTypeClasses OverloadedStrings FlexibleContexts FlexibleInstances NamedFieldPuns
        TupleSections ExistentialQuantification TypeApplications UndecidableInstances BangPatterns ViewPatterns
        GADTs
tests:
  confcrypt-detailed-tests:
    main:                DetailedTests.hs
    source-dirs:
        - test
        - app
    other-modules:
        ConfCrypt.Parser.Tests,
        ConfCrypt.Commands.Tests,
        ConfCrypt.Encryption.Tests,
        ConfCrypt.CLI.API,
        ConfCrypt.CLI.API.Tests,
        ConfCrypt.Common
        Tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - confcrypt
    - tasty
    - tasty-quickcheck
    - QuickCheck
    - tasty-hunit
    - HUnit
    - memory
    default-extensions: MultiParamTypeClasses OverloadedStrings FlexibleContexts FlexibleInstances NamedFieldPuns
        TupleSections

  confcrypt-threshold-tests:
    main:                ThresholdTests.hs
    source-dirs:
        - test
        - app
    other-modules:
        ConfCrypt.Parser.Tests,
        ConfCrypt.Commands.Tests,
        ConfCrypt.Encryption.Tests,
        ConfCrypt.CLI.API,
        ConfCrypt.CLI.API.Tests,
        ConfCrypt.Common,
        ConsoleReporter
        Tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - confcrypt
    - tasty
    - tasty-quickcheck
    - QuickCheck
    - tasty-hunit
    - HUnit
    - memory
    - tagged
    - generic-deriving
    - stm
    default-extensions: MultiParamTypeClasses OverloadedStrings FlexibleContexts FlexibleInstances NamedFieldPuns
        TupleSections
